# Generated by Django 6.0.3 on 2026-03-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['username']},
        ),
    ]
