# Generated by Django 6.0.3 on 2026-03-27 12:40

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.IntegerField(default=2024, help_text='Year of enrollment', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)]),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', help_text="Enter student's first name", max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grade Point Average (0.0 to 4.0)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', help_text="Enter student's last name", max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(help_text='Age must be between 16 and 100', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering')], help_text='Select the branch of study', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(help_text="Student's email address", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload student photo', null=True, upload_to='student_images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(help_text='Unique username for the student', max_length=150, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('email', 'username')},
        ),
    ]
